### ISSUE TITLE
Consider taking bootstrap and jquery out of the base setup

### ISSUE THREAD

**Issue by bradley-stone** [hdavtian/gulp#7]
Not every project is going to be a bootstrap project. My thought is that if people need it, they can install it.

Every project has jquery, but that doesn’t make it right. People really use jquery as a crutch nowadays and they end up loading it for doing show/hide or some stupid sh*t that they can just do with plan js and then we get all that extra overhead.

Maybe people can upvote or downvote this to see if they agree.

**Comment by bradley-stone** [comment]
It sounds like people agree with this. Let's go with it!

**Comment by hdavtian** [comment]
Agreed, I had initially included jquery and bootstrap as examples. A couple of points of clarification:

-'gulp' task is using a task called 'main-bower-files', that's what threw the error you mentioned, because it didn't see the 'bower-components' directory. I will nevertheless remove main-bower-files from the default task.

- 'gulp watch' works without the need to install bower components and instructions actually indicated to use 'gulp watch' and not gulp :)

We need to make a distinction about what each of these 3 tasks do:
- gulp
- gulp watch (<-- works without bower components)
- gulp deploy or production or something like that

**Comment by hdavtian** [comment]
resolved, closing issue
